meta:
  identifier: monster12
  spec: model

clusters:
  - identifier: cluster-c11
nodes:
  - identifier: node1
    cluster: cluster-c11
    compute:
      cpu: 12
      ram: 12
  - identifier: node2
    compute:
      ram: 111
      cpu: 333
