meta:
  identifier: monster-truck

clusters:
  - identifier: cluster-c11
nodes:
  - identifier: node1
    cluster: cluster-c11
    region: us-east-1
    compute:
      cpu: 120
      ram: 12
  - identifier: node2
    region: us-east-1
    compute:
      ram: 111
      cpu: 333
